<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <style>
        .container {
            display: flex;
            justify-content: center;
            align-items: center;
        }

        span {
            color: red;
        }

    </style>
</head>

<body>
    <div class="container">
        <h1>Secure Your Password using <span>BLOWFISH</span> Hasing Algorithm</h1>
    </div>

    <?php
        
        // There are multiple Hasing Algorithms available. some of them are as follows:
        
        // 1. MDA5 ==> Least secure Algorithm

        // 2. SHA-1 ==>

        // 3. SHA-2 ==> SHA-512 , SHA-256

        // 4. AES

        // 5. BLOWFISH ==> MOST SECURE Algorithm , FREE OF COST , SLOW (to decrypt)

        // we will use BLOWFISH algorithm 

        $password = "abcd1234";

        // $cost_value = ['cost' => 12];

        $options = ['cost' => 12 , 'salt' => "Lorem Ipsum is simply dummy text of the printing and typesetting industry."];

        // ^ NOTE : The length of (string) of "salt" must be greater than or equal to 22 , if not then it will throw error.

        $store_password = password_hash($password , PASSWORD_BCRYPT , $options);

        // $store_password = password_hash($password , PASSWORD_BCRYPT , $cost_value);

        echo $store_password . "<br>";

        // 1. encrypted value without cost_value and salt: $2y$10$ngvfASp879E1HErhto6z/u35K1i2p3k0Bll/5z9ieaJiQ2nriVx4K

        // 2. encrypted value after using cost_value : $2y$12$NjGK1cacadmdae4.2pZ5zOBIMexM./sB/ksNm5xcF.12Y/qr/AK3.

        // 3. encrypted value after using cost_value and salt: $2y$12$TG9yZW0gSXBzdW0gaXMgcuY/9kjbEuydSeyjL./CYkjS5WfKpHL7.

        // here , 2y means ==> BLOWFISH algorithm

        // 12 ==> cost is 12 ( denotes the algorithmic cost that should be used and it takes a particular amount of time load / decrypt and as the number is bigger , it takes more time to load a page / decrypt password ) 

        // ^ CONCLUSION : The all 3 values generated by all above 3 conditions (1. , 2. , 3. ) are always different.

    ?>
</body>

</html>